// <auto-generated />
using System;
using Hotel.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hotel.Repository.Migrations
{
    [DbContext(typeof(Database))]
    partial class DatabaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hotel.Repository.Entity.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Hotel.Repository.Entity.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Beds")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Beds = 1,
                            Price = 60,
                            RoomNumber = "100"
                        },
                        new
                        {
                            Id = 2,
                            Beds = 2,
                            Price = 80,
                            RoomNumber = "101"
                        },
                        new
                        {
                            Id = 3,
                            Beds = 3,
                            Price = 100,
                            RoomNumber = "102"
                        },
                        new
                        {
                            Id = 4,
                            Beds = 1,
                            Price = 80,
                            RoomNumber = "200"
                        },
                        new
                        {
                            Id = 5,
                            Beds = 3,
                            Price = 120,
                            RoomNumber = "201"
                        },
                        new
                        {
                            Id = 6,
                            Beds = 2,
                            Price = 90,
                            RoomNumber = "202"
                        },
                        new
                        {
                            Id = 7,
                            Beds = 1,
                            Price = 75,
                            RoomNumber = "300"
                        },
                        new
                        {
                            Id = 8,
                            Beds = 2,
                            Price = 110,
                            RoomNumber = "301"
                        },
                        new
                        {
                            Id = 10,
                            Beds = 3,
                            Price = 160,
                            RoomNumber = "302"
                        },
                        new
                        {
                            Id = 11,
                            Beds = 2,
                            Price = 90,
                            RoomNumber = "400"
                        },
                        new
                        {
                            Id = 12,
                            Beds = 3,
                            Price = 140,
                            RoomNumber = "401"
                        },
                        new
                        {
                            Id = 13,
                            Beds = 1,
                            Price = 100,
                            RoomNumber = "402"
                        },
                        new
                        {
                            Id = 14,
                            Beds = 3,
                            Price = 140,
                            RoomNumber = "500"
                        },
                        new
                        {
                            Id = 15,
                            Beds = 2,
                            Price = 130,
                            RoomNumber = "501"
                        },
                        new
                        {
                            Id = 16,
                            Beds = 1,
                            Price = 150,
                            RoomNumber = "502"
                        });
                });

            modelBuilder.Entity("Hotel.Repository.Entity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@admin.ee",
                            Firstname = "John",
                            IsAdmin = true,
                            Lastname = "Deree",
                            PersonalCode = "12345678910"
                        },
                        new
                        {
                            Id = 2,
                            Email = "petja.petrov@gmail.com",
                            Firstname = "Petja",
                            IsAdmin = false,
                            Lastname = "Petrov",
                            PersonalCode = "10987654321"
                        },
                        new
                        {
                            Id = 3,
                            Email = "dasha.semjonova@gmail.com",
                            Firstname = "Dasha",
                            IsAdmin = false,
                            Lastname = "Semjonova",
                            PersonalCode = "48711270533"
                        },
                        new
                        {
                            Id = 4,
                            Email = "kolja.mashkov@gmail.com",
                            Firstname = "Kolja",
                            IsAdmin = false,
                            Lastname = "Mashkov",
                            PersonalCode = "39012219342"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
